project:
  type: website

website:
  title: "biostat777-intro-lidio-jaimes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        text: About
      - data-analysis.qmd
        text: Example Data Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



