## Education
<span style="color:#003D9C; font-weight:bold;">Johns Hopkins University, Bloomberg School of Public Health</span>
<span style="float: right;">Baltimore, MD</span><br>
Sc.M. in Biostatistics <span style="float: right;">Expected: May 2027</span>


<span style="color:#BA0C2F; font-weight:bold;">The University of Georgia</span>
<span style="float: right;">Athens, GA</span><br>
B.S. in Statistics and Minor in Public Health <span style="float: right;">May 2025</span>

## Research interests
I am interested in survival analysis and longitudinal data analysis, with applications in aging research and clinical trials. I look forward to deepening my expertise in biostatistics and building a meaningful career in the field.

## Research experience

**Biostatistics Research Assistant**, University of Georgia — Athens, GA | Oct 2024 – May 2025  
- Analyzed stroke patient data to identify key factors influencing severity and outcomes  
- Ensured data quality, conducted statistical analyses, and generated visualizations using R  

**Biostatistics Research Assistant**, University of California, Irvine — Irvine, CA | Jun 2024 – Aug 2024  
- Analyzed neuropsychiatric symptoms in Down Syndrome and Alzheimer’s cohorts  
- Conducted data wrangling, visualization, and longitudinal modeling using R with version control via Git/GitHub  

**Biostatistics Research Assistant**, Columbia University — New York, NY | Jun 2023 – Jul 2023  
- Studied medical cost trajectories for lung cancer patients using R  
- Conducted data cleaning, exploratory visualization, and applied survival and nonparametric analyses

## Publications

<p style="margin-left: 0; text-indent: -1.5em; padding-left: 1.5em;">
Magana-Ramirez C., Gillen D., Hom C., <strong>Jaimes L.</strong>, Chilukuri S., McMahon N., Lin C., Kuhlman R., Hu T., Head L., Lott I., & Sultzer D. 
“Neuropsychiatric symptoms and emerging dementia in people with Down syndrome and older adults.” <em>Alzheimer's Dement</em>. 2025; (accepted and in production)
</p>
